### ISSUE TITLE
HTTP 401 not causing code to fall into 'error' path

### ISSUE THREAD

**Issue by sschwartzman** [openmindlab/cctail#1]
Hi @fgiust ! I'm excited to use `cctail`, I'm actually looking into having it pipe the logs to an ingestion tool like fluentd, but that's besides the point right now. ;) For right now though, I'm just playing with it to see how it works today. For an SFCC sandbox for which I don't have an API Client create yet, I tried my personal client_id and secret_id. I would expect this to fail since it is expecting an API Client creds. However when I run it this way, it doesn't throw any 401 failures, it just comes back with an empty log list, like this:
```
seth:cctail $ node dist/cctail.js
cctail - v1.2.0 - (c) openmind

Authenticating using oauth - client_id REDACTED

✔ Select logs on [REDACTED.demandware.net] ›
No log selected, exiting.
```

I added a couple log messages to `logfetcher.ts` to see what's going on, here's the result:
```
seth:cctail $ node dist/cctail.js
cctail - v1.2.0 - (c) openmind

Authenticating using oauth - client_id REDACTED

Response:
{
  error_description: 'Client authentication failed',
  error: 'invalid_client'
}
Status Code: 401

Response: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>401 - Authorization Required.</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>Authorization Required</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		This request requires HTTP authentication.
	</p>
	<hr>
</body>
</html>
Status Code: 401

✔ Select logs on [REDACTED.demandware.net] ›
No log selected, exiting.
```

So it seems the Axios requests are getting 401 errors back (which I would expect!), but the `catch` blocks aren't catching them. I'll keep playing with the code, I suspect it's because it's to do with `await` or how Axios handles error codes.

**Comment by sschwartzman** [comment]
Figured it out! Commented out these 3 lines and it works as it should:

```
// axios.defaults.validateStatus = function () {
//  return true;
// };
```

Should I fork and PR to fix or will you? I noticed you have 2 branches going and the `develop` branch is the active one, wasn't sure if I should touch that though since you may have already fixed this locally!

**Comment by fgiust** [comment]
hi @sschwartzman,
the commented out code is actually needed to handle return codes 416 when polling for new content. Without that you will see cctail failing shortly after the first polling.
I was able to reproduce your error with an invalid client id, I'll see how to fix it without changing the validate status default.

**Comment by sschwartzman** [comment]
Yeah I saw that after I'd put in this issue (or rather, the "figured it out" part). But since then, I've done a whole bunch of refactoring of your code to do some neat things...

- Display logs to stdout (your existing functionality) OR send them to a FluentD collector.
- Works with Client API (your existing functionality) OR Business Manager credentials. If Client API, relies on the bearer token for subsequent API calls and refreshes them if needed (i.e. when they expire).
- Added interceptors to axios to handle concurrent connections. This makes it run a little more slower but resolves all of the 500 errors I was getting when trying to poll multiple logs (at least in my initial testing)
- Run interactively (your existing functionality) OR headless based on config file entries. When headless, it handles rollovers of the logs at 00:00 GMT.

Take a look! I'm still actively working on it, but its functional at the moment. I have it running against an SFCC sandbox right now to see how it holds up overnight.

https://github.com/sschwartzman/cctail/tree/develop

**Comment by sschwartzman** [comment]
Hi @fgiust, I was curious if you'd be willing to accept a PR of my fork back to your repo. When building out my version, I made all attempts to leave the core functionality you have built intact, so the user experience should be no different if you want to use it for simple log tailing. You can even use the existing versions of the config file, as all of the other settings I've added are optional.

I would be happy to continue collaborating with you on this project beyond the initial PR. However, if you would prefer I keep this fork separate, I can do that as well.

If you'd like to discuss in greater depth offline, let me know the method by which you'd prefer to connect. I'd have sent you an email but I couldn't find your address anywhere!

**Comment by fgiust** [comment]
Hi @sschwartzman,
I see you did a great work here, so I will absolutely be happy to accept the PR for merging your contributions back on the project.

The fluentd/non-interactive features look great, I'll try it and review if everything is still working as before for the standard console output. 
One thing that IMHO should need a review is the alternative BM login: I would not actually wanted to add it since it's now deprecated and we are encouraging using client id/secret, but if needed I would better adapt to the standard dw.json format using username/password fields (instead of adding an auth_type this should be driven by filling username/password instead of client_id/secret... more clear that using the same fields as username/password when auth_type is bm).

**Comment by sschwartzman** [comment]
That's great, I'm really glad to hear that. I am trying to put it through its paces with a couple clients soon, hopefully from there I'll work out any kinks in the code. I also need to add test cases for fluent and non-interactive. You're also welcome to try it out and let me know what's busted. ;)

Regarding the BM login, I actually put that in out of necessity, as I didn't have client API creds to test with for a particular client. I think if we specify in the README that it is deprecated and should only be used for test purposes, it should be ok? If we are to keep it in, I agree with your use of the standard dw.json format rather than an extra field. I've already committed the change: https://github.com/sschwartzman/cctail/commit/eb0d56e76d20fa7354cf24e8699f3b04e4cd1b4b

**Comment by sschwartzman** [comment]
Closing since we handled through the PR!

**Comment by fgiust** [comment]
hi @sschwartzman ,
just to let you know: I've merged your PR but I am now properly testing after the changes and I see console mode is actually broken (log tail output back the same last part of the file at any polling). I'll try to review/fix it properly by keeping all your changes anyway.

**Comment by sschwartzman** [comment]
Yeah, I'm sorry about that @fgiust! I found and fixed the bug this morning and added support for the "codeprofiler" csv files too. I PRed my fixes back already, please take a look: https://github.com/openmindlab/cctail/pull/3
